<?php

return [
    'Id'  =>  '自增ID',
    'Group_id'  =>  '分润代理ID',
    'Fenrundate'  =>  '分润日期',
    'Amount'  =>  '分润金额',
    'Realmount'  =>  '实际转账金额',
    'Tran_id'  =>  '微信支付平台订单号',
    'Tran_time'  =>  '微信平台支付时间',
    'Paynote'  =>  '分润转账系统备注',
    'Admin_id'  =>  '操作管理员ID',
    'Createtime'  =>  '创建时间',
    'Updatetime'  =>  '更新时间',
    'Status'  =>  '状态',
    'Accountset.name'  =>  '分润代理名称',
    'Accountset.phone'  =>  '分润代理手机号',
    'Accountset.openid'  =>  '分润个人微信零钱收款ID',
    'Accountset.realname'  =>  '个人微信零钱实名',
    'Accountset.bank_name'  =>  '分润开户行',
    'Accountset.bank_no'  =>  '分润银行卡号',
    'Accountset.true_name'  =>  '分润开户名',
    'Realamount'  =>  '实际转账金额',
    'Num'  =>  '批量转账数量',
    'Content'  =>  '批量转账详情',
];
