<?php

return [
    'Order_no'  =>  '订单号',
    'Users_id'  =>  '用户ID',
    'Phone'  =>  '用户手机',
    'Dev_id'  =>  '设备ID',
    'Admin_id'  =>  '管理员ID',
    'Entity_id'  =>  '设备实体ID',
    'Netpoint_id'  =>  '网点',
    'Price_id'  =>  '价格ID',
    'Lightnight'  =>  '日间夜间标识',
    'Hourprice'  =>  '按时计费价格',
    'Days'  =>  '租用天数',
    'Pricedata'  =>  '价格数据',
    'Pay'  =>  '支付金额',
    'Tran_id'  =>  '微信订单号',
    'Refund'  =>  '退款金额',
    'Refundtime'  =>  '退款时间',
    'Refundnote'  =>  '退款备注',
    'Step'  =>  '订单步骤',
    'Status'  =>  '订单状态',
    'Rtn_admin_id'  =>  '还床操作管理员ID',
    'Createtime'  =>  '创建时间',
    'Netpoint_name'  =>  '网点名称',
    'Devicenums'  =>  '设备数量',
    'Totalorders'  =>  '计费订单总数',
    'Totalamount'  =>  '计费订单金额',
    'Userate'  =>  '设备使用率',
    'Incomerate'  =>  '设备收益率',
    'Hourorders'  =>  '按时订单总数',
    'Houramount'  =>  '按时订单金额',
    'Timesorders'  =>  '按次订单总数',
    'Timesamount'  =>  '按次订单金额',
    'Dayorders'  =>  '按天订单总数',
    'Dayamount'  =>  '按天订单金额',
    'Lightorders'  =>  '日间订单总数',
    'Lightamount'  =>  '日间订单金额',
    'Nightorders'  =>  '夜间订单总数',
    'Nightamount'  =>  '夜间订单金额',
    'Freeorders'  =>  '免费订单总数',
    'Endtime'  =>  '时段查询'
];
