<?php

return [
    'Id'  =>  '主键ID',
    'Dev_id'  =>  '设备ID',
    'Price_id'  =>  '价格ID',
    'Netpoint_id'  =>  '网点ID',
    'Entity_id'  =>  '实体类型ID',
    'Admin_id'  =>  '管理员ID',
    'Department'  =>  '科室',
    'Room'  =>  '病房',
    'Bed'  =>  '病床',
    'Iscabinet'  =>  '是否储物柜',
    'Mac'  =>  '设备mac',
    'Blekey'  =>  '蓝牙秘钥',
    'Blepwd'  =>  '开锁密码',
    'Mac2'  =>  '抽屉mac',
    'Blekey2'  =>  '抽屉秘钥',
    'Blepwd2'  =>  '抽屉开锁密码',
    'Createtime'  =>  '创建时间',
    'Updatetime'  =>  '更新时间',
    'Status'  =>  '状态',
    'Netpoint.admin_id'  =>  '管理员ID',
    'Netpoint.name'  =>  '网点名称',
    'Entity.name'  =>  '实体名称',
    'Price.name'  =>  '价格名称',
    'Price.lightstart'  =>  '日间可用开始时间',
    'Price.lightend'  =>  '日间可用结束时间',
    'Price.nightstart'  =>  '夜间可用开始时间',
    'Price.nightend'  =>  '夜间可用结束时间',
    'Price.hourdeposit'  =>  '按时租押金',
    'Price.hourprice'  =>  '小时收费价格',
    'Price.timesdeposit'  =>  '按次租押金',
    'Price.lighttimesprice'  =>  '日间按次收费价格',
    'Price.nighttimesprice'  =>  '夜间按次收费价格',
    'Price.daydeposit'  =>  '按日租押金',
    'Price.dayprice'  =>  '按日租用价格',
    'Devtype.name'  =>  '设备类型'
];
