<?php

return [
    'Id'  =>  '自增ID',
    'Users_id'  =>  '用户ID',
    'Device_id'  =>  '设备ID',
    'Netpoint_id'  =>  '网点ID',
    'Entity_id'  =>  '实体类型ID',
    'Admin_id'  =>  '维护人员ID',
    'Title'  =>  '故障标题',
    'Issue_images'  =>  '故障图片',
    'Issue_desc'  =>  '故障描述',
    'Fixdesc'  =>  '处理结果描述',
    'Status'  =>  '状态',
    'Createtime'  =>  '创建时间',
    'Updatetime'  =>  '更新时间',
    'Netpoint.name'  =>  '网点名称',
    'Netpoint.shortname'  =>  '网点简称',
    'Netpoint.netaddr'  =>  '网点地址',
    'Netpoint.netlng'  =>  '网点经度',
    'Netpoint.netlat'  =>  '网点纬度',
    'Entity.name'  =>  '实体名称',
    'Entity.entity_image'  =>  '实体图片',
    'Users.phone'  =>  '用户手机',
    'Users.nickname'  =>  '昵称',
    'Users.wxgender'  =>  '微信性别',
    'Admin.name'  =>  '维护人员',
];
